### ISSUE TITLE
Non working

### ISSUE THREAD

**Issue by pandeo** [tuyennn/Vietnamese_Checkout#1] opened 2017-11-04 21:16 UTC
Hello. Trying to install it - doesnt replace default checkout. I see no action.

**Comment by tuyennn** [comment] 2017-11-04 22:12
Please make sure you enable it in configuration

**Comment by pandeo** [comment] 2017-11-04 22:46
Hello, i did :) Nothing happen 

Sergey
Spearfisher & Diver
---------------------------------------------------------
© 2006-2016 Sia Ipsum.All Rights Reserved

Skype: eurodiveshop
Phone: +371-25141045
www.eurodiveshop.com

Stay Tuned on Facebook
http://www.facebook.com/Eurodiveshop <http://www.facebook.com/Eurodiveshopa>

**Comment by tuyennn** [comment] 2017-12-20 08:22
Hi @pandeo 
Confirm your issue, this was caused by missing layout. This was fixed on [ce3be1f](https://github.com/tuyennn/Vietnamse_Checkout/commit/ce3be1f533493d14e30cfeb741f4144c677fb831)

**Closed as completed** 2017-12-20 08:24 UTC
Labels: bug
